spring:
  profiles:
    active: prd
  data:
    jpa:
      repositories:
        enabled: true
  http:
    encoding:
      charset: UTF-8
    multipart:
      enabled:  true
      file-size-threshold: 1MB
      max-file-size:  10MB
      max-request-size:  10MB
  jpa:
    properties:
      hibernate:
        generate_statistics: false
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
security:
  enable-csrf: false
  basic:
    enabled: false
server:
  tomcat:
    uri-encoding: UTF-8
  session:
    timeout: 3600
wechat:
  mp:
    appId: wxd45ea849e28c0d42
    secret: 6b14f343294929d96ff1be2f720d130b
    token: hlwerbv123nsf
    aesKey: u3hX2kQdo1hvQWRkg9MjOahuw3zY7nxmargMNf9TJW7
  pay:
    appId: wxd45ea849e28c0d42
    mchId: 1487336252
    mchKey: 134fafasdfqwerqwersv12231fqqer1a
    subAppId:
    subMchId:
    keyPath: C:/Users/zhanwa01/nielsen_space/dlsw/shopping/src/main/resources/cert/apiclient_cert.p12
sms:
  appId: 1400048750
  appKey: 0721e3b884a93f0d3092a32f6e4c4f09
  regTempId: 33761
  pwFoundTempId: 33989
---
server:
  port: 8080
spring:
  devtools:
    livereload:
      enabled: true
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
            indexBase: C:\project\dlsw\lucene\indexes
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      #url: jdbc:mysql://598af1f083b62.sh.cdb.myqcloud.com:5428/dlsw?useUnicode=true&characterEncoding=utf-8&useSSL=false
      url: jdbc:mysql://localhost:3306/dlsw
      username: root
      password: 123456
      connectionInitSqls: set names utf8mb4;
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  http:
    multipart:
      location: c:/upload_temp
management:
  port: 54001
  health:
    sensitive:
      enabled: false
web:
  maximumSessions: 100
photo:
  path: c:/project/dlsw/shopping/photo/
  payCentPath: c:/project/dlsw/shopping/payCentPath/
flush:
  path: http://localhost:8080/api/user/flushUserRoleType
wechat:
  pay:
    keyPath: /sdb1/projects/dlsw/shopping/apiclient_cert.p12
    payNotice: http://www.zgdl.net.cn/api/wechat/pay/payNotice
  login:
    defaultPwd: ~!@Wz718718
    loginCallback: http://www.zgdl.net.cn/api/wechat/user/weLoginCallback
    bindPhonePath: http://www.zgdl.net.cn/bindPhone.html
    loginSuccessPath: http://www.zgdl.net.cn/u.html
---
server:
  port: 8888
spring:
  profiles: st
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
            indexBase: /sdb1/projects/dlsw_st/lucene/indexes/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://598af1f083b62.sh.cdb.myqcloud.com:5428/dlsw_st
    username: root
    password: wz718718
    initialSize: 5
    connectionInitSqls: set names utf8mb4;
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  http:
    multipart:
      location: /sdb1/projects/dlsw_st/temp
web:
  maximumSessions: 100
photo:
  path: /sdb1/projects/dlsw_st/photo/
  payCentPath: /sdb1/projects/dlsw_st/photo/
flush:
  path: http://127.0.0.1:8888/api/user/flushUserRoleType
wechat:
  pay:
    keyPath: /sdb1/projects/dlsw/shopping/apiclient_cert.p12
    payNotice: http://www.zgdl.net.cn/api/wechat/pay/payNotice
  login:
    defaultPwd: ~!@Wz718718
    loginCallback: http://www.zgdl.net.cn/api/wechat/user/weLoginCallback
    loginSuccess: http://www.zgdl.net.cn/bindPhone.html
---
server:
  port: 80
spring:
  profiles: prd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
            indexBase: /sdb1/projects/dlsw/shopping/lucene/indexes/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.14:3306/dlsw
    username: root
    password: wz718718
    connectionInitSqls: set names utf8mb4;
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  http:
    multipart:
      location: /sdb1/projects/dlsw/shopping/temp
web:
  maximumSessions: 100
photo:
  path: /sdb1/projects/dlsw/shopping/photo/
  payCentPath: /sdb1/projects/dlsw/shopping/photo/
flush:
  path: http://www.zgdl.net.cn/api/user/flushUserRoleType
wechat:
  pay:
    keyPath: /sdb1/projects/dlsw/shopping/apiclient_cert.p12
    payNotice: http://www.zgdl.net.cn/api/wechat/pay/payNotice
  login:
    defaultPwd: ~!@Wz718718
    loginCallback: http://www.zgdl.net.cn/api/wechat/user/weLoginCallback
    bindPhonePath: http://www.zgdl.net.cn/bindPhone.html
    loginSuccessPath: http://www.zgdl.net.cn/u.html