spring:
  #resources.static-locations: classpath:/dist/
  profiles:
    active: prd
  data:
    jpa:
      repositories:
        enabled: true
  http:
    encoding:
      charset: UTF-8
    multipart:
      enabled:  true
      file-size-threshold: 1MB
      max-file-size:  10MB
      max-request-size:  10MB
  jpa:
    properties:
      hibernate:
        generate_statistics: false
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
security:
  enable-csrf: false
  basic:
    enabled: false
server:
  tomcat:
    uri-encoding: UTF-8
  session:
    timeout: 3600
sms:
  appId: 1400048750
  appKey: 0721e3b884a93f0d3092a32f6e4c4f09
  regTempId: 33761
  pwFoundTempId: 33989
---
server:
  port: 8090
spring:
  devtools:
    livereload:
      enabled: true
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
            indexBase: C:\project\dlsw\lucene\indexes
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://sh-cdb-3ntvx5ni.sql.tencentcdb.com:63781/dlsw?useSSL=false
      username: root
      password: wz718718
      connectionInitSqls: set names utf8mb4;
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  http:
    multipart:
      location: c:/upload_temp
web:
  maximumSessions: 100
---
server:
  port: 8091
spring:
  profiles: st
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
            indexBase: /sdb1/projects_st/lucene/indexes/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://598af1f083b62.sh.cdb.myqcloud.com:5428_st
    username: root
    password: wz718718
    initialSize: 5
    connectionInitSqls: set names utf8mb4;
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  http:
    multipart:
      location: /sdb1/projects_st/temp
web:
  maximumSessions: 100
---
---
server:
  port: 8093
spring:
  profiles: prd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
            indexBase: /sdb1/projects/cms/lucene/indexes/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.14:3306?useSSL=true
    username: root
    password: wz718718
    connectionInitSqls: set names utf8mb4;
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  http:
    multipart:
      location: /sdb1/projects/cms/temp
web:
  maximumSessions: 100
wechat:
  pay:
    keyPath: /sdb1/projects/cms/apiclient_cert.p12